<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DouDouDeDou</RootNamespace>
    <AssemblyName>抖抖的抖</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Icons\app-icon.ico</ApplicationIcon>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.XInput" Version="3.6.2" />
    <PackageReference Include="HidSharp" Version="2.6.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="config.default.json" CopyToOutputDirectory="PreserveNewest" />
    <Resource Include="Assets\Images\*.png" />
    <Resource Include="Assets\Icons\*.png" />
    <Resource Include="Assets\UI\*.png" />
    <Resource Include="Assets\References\*.png" />
    <Resource Include="Assets\Controllers\**\*.svg" />
    <Resource Include="Assets\Controllers\**\*.xaml" />
    <Resource Include="Assets\Themes\*.xaml" />
  </ItemGroup>
</Project>

